captainVersion: 4
services:
    $$cap_appname-db:
        image: bitnami/$$cap_db_type:$$cap_database_version
        volumes:
            - $$cap_appname-db-data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: $$cap_db_pass
            MYSQL_DATABASE: drupal
            MYSQL_USER: $$cap_db_user
            MYSQL_PASSWORD: $$cap_db_pass
            MARIADB_ROOT_PASSWORD: $$cap_db_pass
            MARIADB_DATABASE: drupal
            MARIADB_USER: $$cap_db_user
            MARIADB_PASSWORD: $$cap_db_pass
        caproverExtra:
            notExposeAsWebApp: 'true'
    $$cap_appname:
        depends_on:
            - $$cap_appname-db
        image: bitnami/drupal:$$cap_drupal_version
        volumes:
            - $$cap_appname-drupal-data:/bitnami/drupal
        restart: always
        environment:
            DRUPAL_DATABASE_HOST: srv-captain--$$cap_appname-db
            DRUPAL_DATABASE_USER: $$cap_db_user
            DRUPAL_DATABASE_PASSWORD: $$cap_db_pass
            DRUPAL_DATABASE_NAME: drupal
        caproverExtra:
            containerHttpPort: '8080'
caproverOneClickApp:
    variables:
        - id: $$cap_db_user
          label: Database user
          defaultValue: drupal
          validRegex: /^([a-zA-Z0-9])+$/
        - id: $$cap_db_pass
          label: Database password
          description: ''
          validRegex: /^(\w|[^\s"'\\])+$/
        - id: $$cap_drupal_version
          label: Drupal Version
          defaultValue: 'latest'
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/bitnami/drupal/tags/
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_db_type
          label: Database Type
          defaultValue: mariadb
          description: You can either choose mariadb or mysql, you need to change the version according to which DB is selected. It is case sensitive.
          validRegex: /^(mysql|mariadb)$/
        - id: $$cap_database_version
          label: Database Version, default is MariaDB latest
          defaultValue: 'latest'
          description: Check out the Docker pages for the valid tags https://hub.docker.com/r/library/mysql/tags/ or https://hub.docker.com/_/mariadb?tab=tags
          validRegex: /^([^\s^\/])+$/
    instructions:
        start: >-
            Drupal is one of the most versatile open source content management systems on the market.

            Drupal is built for high performance and is scalable to many servers, has easy integration via REST, JSON, SOAP and other formats, and features a whopping 15,000 plugins to extend and customize the application for just about any type of website.
        end: >
            Drupal is deployed and available as $$cap_appname.

            IMPORTANT: It will take up to 2 minutes for Drupal to be ready. Before that, you might see a 502 error page.
    displayName: Drupal
    isOfficial: true
    description: Drupal is one of the most versatile open source content management systems on the market.
    documentation: Taken from https://hub.docker.com/r/bitnami/drupal.
